### PR TITLE
Update code of conduct to properly align to the behavior observed from DHH.

### PR DESCRIPTION
**Pull request by LizAinslie**
I haven't been personally active in the Rails community for quite some time now, and this library change personally does not affect me, but it's sad to see this is happening right now.

I see clear disrespect, obsoleting valuable PRs by making rash decisions without conferring with the community in #971, completely ignoring a valid argument by @t3dotgg saying "maybe this isn't the project for you" in #977. What happened in #977 doesn't really break the code of conduct, but it certainly isn't welcoming which is outlined as the interest of the Code of Conduct:

I see you calling members of your project's community "Hooligans". Everybody is free to share their disagreement in a harm free manner, and I see no harm being done by those you have called out in your blog post. @scorbettUM and @t3dotgg are both valuable members of the wider OSS community whose words carry far more weight than mine even in our "dogmatic circle" as you so call it.

I'm certain this PR will get closed and locked as the rest have (and I see it's already been done by someone I don't recognize!). Before that happens @dhh, I ask you this: Do you have what it takes to accept this PR and admit that "community doesn't matter" is your mindset? If that is the case, I can see forks being made and favored by most as a likely outcome from this point forward. If you don't admit to it, the same thing will likely happen, but slower. 

These are **your** options, and the future of **your** project relies on **your** decisions. Like you and many others have said, it is "your" project. The community can fork it and maintain it how they see fit. I hope they know that this is what they have to do, because your mind is made up for the path you think is best.

### CODE REVIEW

**Comment by LizAinslie** [comment]
It is worth noting this behavior has also been exhibited by the maintainer of Serde in the rust community and the "maintainer" of Twitter. It is truly sad to watch.

**Comment by Qodestackr** [comment]
> It is worth noting this behavior has also been exhibited by the maintainer of Serde in the rust community and the "maintainer" of Twitter. It is truly sad to watch.

While every opinion is valid. I think his behavior and seeing "hooligans" rather than contributors side of view is terrible. Anyway TS has me building type safe APIs and I have nothing to do with turbo. This hostility should end😹

**Comment by LizAinslie** [comment]
> Anyway TS has me building type safe APIs and I have nothing to do with turbo. This hostility should end😹

true that xD

**Comment by janosrusiczki** [comment]
At this point I'm pretty sure DHH does things just so he can then write about the inevitable backlash. :smile:

Next up: DHH removes Ruby from Ruby on Rails.

**Comment by javierav** [comment]
> I haven't been personally active in the Rails community for quite some time now, and this library change personally does not affect me, but it's sad to see this is happening right now.

This is the typical comment from someone who found out about the change on Twitter and is too bored to argue.

This project uses the MIT license. If someone doesn't like the decisions of the main person in charge, they are free to fork and maintain a project to their liking.

**Comment by janosrusiczki** [comment]
> This project uses the MIT license. If someone doesn't like the decisions of the main person in charge, they are free to fork and maintain a project to their liking.

Yeah, but since _the community_ helped bring this project to this point wouldn't it be fair to ask for said community's opinion before important changes such as these are implemented?

**Comment by javierav** [comment]
> Yeah, but since _the community_ helped bring this project to this point wouldn't it be fair to ask for said community's opinion before important changes such as these are implemented?

And we are all grateful to those who contribute with their free time to improve the open source community. But contributing to a project shouldn't give you the power to decide the direction of the project. You freely contribute without expecting anything in return. In open communities, someone always has to take the helm so that false democracy does not make the project ungovernable. IMHO.

**Comment by janosrusiczki** [comment]
@javierav First of all thanks for your answer. I can see the logic behind your arguments but that doesn't necessarily mean I fully agree with them. However, I haven't maintained large OS projects so I don't really know what it implies.

**Comment by jaredcwhite** [comment]
> And we are all grateful to those who contribute with their free time to improve the open source community. But contributing to a project shouldn't give you the power to decide the direction of the project. You freely contribute without expecting anything in return. In open communities, someone always has to take the helm so that false democracy does not make the project ungovernable. IMHO.

Oh hell naw. This is a terrible way to run an open source project, and as an OSS maintainer I can definitively say this is not how I run any of my projects.

I _do_ expect something in return when I contribute to projects, and furthermore I fully expect that _other people will expect something_ when they contribute to projects I maintain: the common courtesy of addressing their feedback and concerns respectfully.

I have re-opened issues and PRs that I'd previously closed after some more context has been provided and I realize, oh right, you have a point there. I also don't recall ever opening a PR that _dramatically changed_ the structure of a codebase and how people are able to contribute to it and then merging that PR _on the same day_ as part of a **publicity stunt** with no community feedback process in place.

**There is no place for that nonsense in open source.**

**Review by Biigode — COMMENTED** [review]
Lgtm :rocket:

**Review by Biigode — APPROVED** [review]

**Review by hinsxd — APPROVED** [review]

**Comment by vtrduque** [comment]
lmao

**Comment by Wazbat** [comment]
I feel these changes are valid, considering the response to #977

If the company wishes to proceed in a particular direction against the opinion of contributors, then the CoC should be updated to reflect this

**Comment by vemv** [comment]
In the wise words of one widely recognised OSS author:

> The only people entitled to say how open source 'ought' to work are people who run projects, and the scope of their entitlement extends only to their own projects.

> Just because someone open sources something does not imply they owe the world a change in their status, focus and effort, e.g. from inventor to community manager.

> As a user of something open source you are not thereby entitled to anything at all. You are not entitled to contribute. You are not entitled to features. You are not entitled to the attention of others. You are not entitled to having value attached to your complaints. 

https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9

Those words were of big influence within the (already respectful) Clojure community and helped us understand better our role as producers and consumers of OSS (I happen to be both, currently for a living).

I hope they're useful to anyone else reading here!

**Pull request closed without merging**
