### PR TITLE
Fix for get response html/text in locked body

### PR DESCRIPTION
**Pull request by ferdyrurka**
Hi,

I detected a small bug during migrating from turbolinks to turbo. :)

Zrzut ekranu z 2021-08-30 20-19-56

It appears when he wants to get `responseHTML` or `responeText` on event: `turbo: before-fetch-response`

### CODE REVIEW

**Comment by dhh** [comment]
Nice. Could you add a test as well?

**Comment by ferdyrurka** [comment]
sure, tomorrow I will add tests :)

**Comment by marphi** [comment]
@ferdyrurka Does this pr resolve issue #19?

**Comment by ferdyrurka** [comment]
@marphi yes :)


I checked this use case it with the following code:

```
document.addEventListener('turbo:submit-end',  async (event) => {
    console.log(await event.detail.fetchResponse.responseHTML)
});
```

**Pull request merged**
