### PR TITLE
Remove Turbo

### PR DESCRIPTION
**Pull request by TheCactusBlue**

### CODE REVIEW

**Review by elias-plank — APPROVED** [review]
LGTM👍

**Review by MashhoodIjaz — APPROVED** [review]

**Review by BilalBudhani — CHANGES_REQUESTED** [review]
you don't get to sabotage a project just because it doesn't agree with your worldview.

**Comment by mauricioklein** [comment]
It's past 15 min.

Can we get it merged?

**Review by mantikafasi — APPROVED** [review]

**Review by rlesniak — APPROVED** [review]

**Comment by Charles-Mwaniki** [comment]
LGTM

**Review by mrcnk — APPROVED** [review]

**Review by Decencies — APPROVED** [review]

**Pull request closed without merging**
