### PR TITLE
Introducing the turbo:after-stream-render event

### PR DESCRIPTION
**Pull request by kapantzak**
This PR introduces the `turbo:after-stream-render event` event that gets fired right after any stream action has been performed.

**Why?**
Someone might need to perform an action based on an element that has been rendered by a stream response. We cannot rely on `turbo:before-stream-render` event for this kind of action because the requested element probably had not been rendered yet.

### CODE REVIEW

**Comment by seanpdoyle** [comment]
Is this a duplicate of #92, #408, and https://discuss.hotwired.dev/t/event-to-know-a-turbo-stream-has-been-rendered/1554/6?

**Comment by kapantzak** [comment]
Hi Sean, to be honest, I wasn't aware of the already closed issues.

What led me to open a PR about this event was the case where we wanted to call a function a soon as a stream was rendered. We thought of the stimulus solution that you propose here, but, as soon as there are quite a lot of partials that get rendered via this stream, we would have to bind the stimulus controller to many places inside the code. Instead, if we had the `turbo:after-stream-render` event available, we could add an event listener once, and handle any event occurrence accordingly. In other words, this would help us to minimize the interventions inside the codebase.

Now, regarding the fact that the event gets fired on the document, we could change this and fire it on the stream element itself.

**Comment by acetinick** [comment]
I have some situations where this is very useful,  namly initializing UI components after the stream renders.  eg. Bootstrap tooltips etc.

**Comment by samstickland** [comment]
Hi @kapantzak,

Did you get any further on this PR. We have the same use case as @acetinick, where we want to bind JS for UI controls in the returned HTML. This would be much more efficient if the event fired on the stream element, but it would also work for us if it was only on the document.

**Comment by kapantzak** [comment]
Hi @samstickland ,

I think that it's better to fire this event on the stream element, as you said. I will try to continue with this asap!

**Comment by kapantzak** [comment]
I have made some changes so that the event is triggered from the target element, but I see that some irrelevant tests fail

**Comment by woto** [comment]
It helped me https://github.com/hotwired/turbo/pull/20#issue-773325276. Didn't found any drawbacks yet.

**Pull request closed without merging**
