### PR TITLE
Update and rename CODE_OF_CONDUCT.md to CODE_OF_SUBMISSION.md

### PR DESCRIPTION
**Pull request by Codinak**
In accordance to https://github.com/hotwired/turbo/issues/977#issuecomment-1709951236

### CODE REVIEW

**Comment by xlmnxp** [comment]
lgtm

**Comment by jt3k** [comment]
Impossible to read! The file history is lost. Make two commits: first, rename the file. Then text edits. 

Removing Typescript will benefit everyone. Ultimately, technology is moving to such a level that soon no typescripts will be needed. I am sure that in the future all types will be derived based on Ai. Stop slowing down progress

**Comment by Codinak** [comment]
@jt3k you can check `update CoC` commit directly now.

**Comment by lonelyteapot** [comment]
This seems to be an exact representation of how @dhh sees open source. "We own the project, you work for free for us."

**Pull request closed without merging**
