### PR TITLE
Fix pausable rendering for previews

### LINKED ISSUE #313: Pauseable rendering breaks after rendering preview
If the fetch response completes before the paused preview render completes, the visit will attempt to render twice whilst a render is in progress, raising:
https://github.com/hotwired/turbo/blob/49f82135e2a5ec8e3279f78373d69214d06a34fa/src/core/view.ts#L50

A quick fix is to disable previews, but ideally, in the case of animating page transitions, the preview would animate in first, and then be seemlessly replaced by the server response.

### PR DESCRIPTION
**Pull request by kirillplatonov**
Resolves #313

### CODE REVIEW

**Comment by kirillplatonov** [comment]
@domchristie it should solve the issue for preview. If fetch will finish before preview rendering is complete - it will wait for it and then just replace the content without a second pause.

**Comment by dhh** [comment]
Think this needs a bump after I merged Dom's fix for same-page anchor links.

**Comment by kirillplatonov** [comment]
@dhh this test keeps failing in Chrome even on main. Investigating.
> chrome on linux - FrameTests - evaluates frame script elements on each render (0.2s)

**Comment by domchristie** [comment]
Thanks @kirillplatonov! That fixes the error, but unfortunately it still results in some unexpected behaviour. When rendering the response after a preview, the `before-render` event is not pausable. For example:

```js
addEventListener('turbo:before-render', (event) => {
  event.preventDefault()
  console.time('RENDER')
  setTimeout(() => event.detail.resume(), 2000)
})

addEventListener('turbo:render', (event) => {
  console.timeEnd('RENDER')
})
```

The timer should always be ~2000ms. It is for the preview, and for visits with no preview, but it's immediate for the render after a preview. Hope that makes sense!? Here's a demo: https://glitch.com/edit/#!/scratched-held-mistake?path=public%2Fscript.js%3A1%3A39

**Comment by kirillplatonov** [comment]
@domchristie It was done intentionally to replace the preview without interception:
https://github.com/hotwired/turbo/blob/main/src/core/view.ts#L79

We can get rid of it. But in that case, both preview and real response will be animated. How do you think it should work?

**Comment by domchristie** [comment]
To provide a bit more context: if the response completes whilst the preview is animating in, the new page will appear to animate twice. The animations will start on the preview, then once the response HTML comes in, the animations restart on the new HTML—it looks a bit glitchy. 

I naively thought that replacing the body would just carry on the animation as it left off; but now I think about it, whenever an element is rendered, any applicable animations will appear to restart.

Now I'm thinking it might be preferable to wait for the preview animations to complete before resuming with the response render. It's possible to determine whether a render is a preview or not, so we can switch off animations for the response. For a visit with a preview, the flow might look something like:

1. animate out
2. wait for animate out then animate in the preview
3. wait for the preview to animate in then immediately render the response

I _think_ that might work?

**Comment by kirillplatonov** [comment]
It should already work this way. The only concern I have is that we probably should skip animation inside the event handler, not in the core. So the example might looks like that:
```javascript
document.addEventListener('turbo:before-render', async (event) => {
  event.preventDefault()
  // Skip animation for response if preview is rendered
  if (document.documentElement.hasAttribute("data-turbo-preview")) {
    await animateOut()
  }
  event.detail.resume()
})
```
And then we won't need to check if preview is rendered here: https://github.com/hotwired/turbo/blob/main/src/core/view.ts#L79

What do you think?

**Comment by domchristie** [comment]
> It should already work this way. The only concern I have is that we probably should skip animation inside the event handler, not in the core.

Unfortunately, I think the `!previewIsRendered` is preventing it from working this way. Your example is exactly what I had in mind. (And always allowing developers to pause a render is a more consistent API 👍)

**Comment by kirillplatonov** [comment]
Sounds good. Prepared a fix: https://github.com/hotwired/turbo/pull/316

**Pull request merged**
